name: tendermint_liquidity
description: Bottle API client library.
version: 1.0.0-v1beta.1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  protobuf: ^2.0.1
  grpc: ^3.0.0


dev_dependencies:
  lint: any